### ISSUE TITLE
Focalboard: Instructions to run the prebuild step before running the make linux-app for standalone desktop app

### ISSUE THREAD

**Issue by imasdekar** [mattermost/mattermost-developer-documentation#1079]
#### For focalboard dev setup the following error is received if prebuild is not run before `make linux-app`

```shell npm run pack

> focalboard@7.2.0 pack
> cross-env NODE_ENV=production webpack --config webpack.prod.js

sh: line 1: cross-env: command not found
make: *** [Makefile:158: webapp] Error 127
```

Hence the [focalboard documentation](https://developers.mattermost.com/contribute/focalboard/personal-server-setup-guide/#building-and-running-standalone-desktop-apps) should clearly state the developer to run the `make prebuild` step before the `make linux-app` step.
The above applies for `make win-wpf-app` & `make mac-app` steps

An issue for the above error is already raised and discussed in [focalboard github repo](https://github.com/mattermost/focalboard).
The related focalboard issue: https://github.com/mattermost/focalboard/issues/3221

**Comment by chenilim** [comment]
Cleaning up old issues. I believe this has been resolved, so closing. Please reopen if there is still outstanding changes needed. Thanks everyone! cc @imasdekar, @justinegeffen.
