### ISSUE TITLE
Update E2E test guidance to use new path

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost-developer-documentation#1086]
[Current documentation ](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) mention that 
> Change directory to `mattermost-webapp/e2e`, and install npm dependencies by running `npm i`

I think correct path should be `mattermost-webapp/e2e/cypress` to install dependencies and run npm test. 

Because when I run `npm run cypress:run` in `mattermost-webapp/e2e`, I receive this error: `Missing script: "cypress:open"`

Tagging @saturninoabril for visibility

**Comment by sinansonmez** [comment]
Okay I just realized that this change is already done by this [PR](https://github.com/mattermost/mattermost-developer-documentation/pull/1055) but the changes are not reflected to website

**Comment by saturninoabril** [comment]
Thanks for looking @sinansonmez! I'll check with the team responsible for deploying the latest documentation.

**Comment by saturninoabril** [comment]
I just checked and the change in the referenced PR is already deployed. However, there are pages that still need to be updated like the one you initially pointed out. We'll update accordingly.

**Comment by sinansonmez** [comment]
Thanks for the information @saturninoabril

**Comment by saturninoabril** [comment]
@sinansonmez I'm closing this issue in favor of the PR submitted - https://github.com/mattermost/mattermost-developer-documentation/pull/1088. Feel free to comment in the PR itself. Again, thanks for looking!
