### ISSUE TITLE
Help Wanted: Add alternative text to all visual assets across the developer documentation site

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/mattermost-developer-documentation#1141]
**Problem space**
Currently, visual assets on developer documentation pages are often missing alternative text which results in this visual content not being accessible by documentation visitors using screen reader technologies. 

**Target audience**
All users, and particularly those using screen reader technologies

**Goal**
- Identify all visual assets across the documentation site that are currently missing alternative text
- Develop and incorporate descriptive alternative text in Markdown format for each visual asset included in the developer documentation

**Delivery expectations**
- 1 PR per documentation page that would benefit from visual elements 
- Refer to alternative text incorporated into visual elements within the [Mattermost Product Documentation](https://docs.mattermost.com/) as a guide to developing alternative text for developer documentation.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Markdown format
- Hugo

**Affected repository**
mattermost/mattermost-developer-documentation

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by EshaanAgg** [comment]
Hi! I would like to work on this issue.
Can you assign me any documentation pages to get started with?

**Comment by cwarnermm** [comment]
@EshaanAgg - Thank you for addressing this developer documentation issue. The [Incoming webhooks](https://developers.mattermost.com/integrate/webhooks/incoming/) page is a good example of a visual asset that is missing alternative text.

**Comment by abhishek-sultaniya** [comment]
Hello @cwarnermm ! I would also like to work on this issue.
Can you assign me any documentation pages to get started with?

**Comment by cwarnermm** [comment]
@abhishek-sultaniya - This issue has been assigned to another contributor.

**Comment by cwarnermm** [comment]
Closed via https://github.com/mattermost/mattermost-developer-documentation/pull/1147
