### ISSUE TITLE
Help Wanted: Correct developer documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/mattermost-developer-documentation#1144]
Correct the error present in the developer documentation that describes [how to create a personal access token](docs.mattermost.com/developer/personal-access-tokens.html#creating-a-personal-access-token).   

Personal Access Tokens managed via user's profile, not Account Settings.

**Step 6** says to go **Account Settings** but the UI for creating access tokens is available within the user's profile instead.

**Comment by leonardonatali** [comment]
Hello! i would like work on this ticket!

**Comment by techsnap** [comment]
Hi, I would like to work on this issue.

**Comment by rsarthak** [comment]
I would like to work on this issue, please assign it to me.

**Comment by Shamik1836** [comment]
Hi, I would like to work on this issue, since it's going to be my first contribution I would like to start from here

**Comment by cwarnermm** [comment]
Thank you for all of the interest in this documentation issue! @techsnap - You were first to comment, and I'm assigning this ticket to you.

@rsarthak & @Shamik1836 - Please let me know if there are other documentation tickets you'd like to work on!

**Comment by rsarthak** [comment]
@cwarnermm I would like to work on #1140 .

**Comment by abhishek-sultaniya** [comment]
> Thank you for all of the interest in this documentation issue! @techsnap - You were first to comment, and I'm assigning this ticket to you.
> 
> @rsarthak & @Shamik1836 - Please let me know if there are other documentation tickets you'd like to work on!

I would like to work on other documentation tickets.
It would be great if you will assign me.

**Comment by cwarnermm** [comment]
Hi @rsarthak - https://github.com/mattermost/mattermost-developer-documentation/issues/1140 has been assigned to someone else.

Hi @abhishek-sultaniya - Please feel free to review the list of product or developer documentation issues. The Docs team will continue to add to the list of Help Wanted tickets throughout Hacktoberfest. When you see an issue that appeals to you, and it hasn't already been claimed by another contributor, comment on that PR and I'll assign it to you.

**Comment by techsnap** [comment]
Hey @cwarnermm, did you mean [this link](https://docs.mattermost.com/developer/personal-access-tokens.html#creating-a-personal-access-token) instead?

I think the rst file for this webpage is [personal-access-tokens.rst](https://github.com/mattermost/docs/blob/master/source/archive/personal-access-tokens.rst)

This is in mattermost/docs repository. Should I edit this file for this issue? And the correct instruction should be the one mentioned in step 6 in [_index.md](https://github.com/mattermost/mattermost-developer-documentation/blob/master/site/content/integrate/reference/personal-access-token/_index.md). Am I right?

**Comment by cwarnermm** [comment]
@techsnap - Good question! I did intend the developers.mattermost.com link. The link in the product docs you provided is an archived file that should no longer be available in production. It's still live as a cached file which needs to be cleared.

**Comment by techsnap** [comment]
Okay. So, do I have to clear that file? Can you clarify more on what do I have to do for this issue now?

**Comment by cwarnermm** [comment]
@techsnap - This ticket asks that you correct the error present in the developer documentation that describes [how to create a personal access token](docs.mattermost.com/developer/personal-access-tokens.html#creating-a-personal-access-token).

**Comment by cwarnermm** [comment]
@techsnap -This Help Wanted is a duplicate unfortunately. This documentation correction was applied via https://github.com/mattermost/mattermost-developer-documentation/pull/1107

I apologize for the confusion and churn this duplication has caused.

**Comment by techsnap** [comment]
No problem!
