### ISSUE TITLE
Unable to setup the docs on local

### ISSUE THREAD

**Issue by Harshil-Jani** [mattermost/mattermost-developer-documentation#1149]
While setting up the documentation site on my local using hugo I am getting an error. 

```shell script
hugo server --buildDrafts --disableFastRender -F -s site
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-23T16:47:50Z VendorInfo=ubuntu:0.92.2-1
ERROR 2022/10/10 20:42:11 failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input
ERROR 2022/10/10 20:42:11 failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input
ERROR 2022/10/10 20:42:11 failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input
Error: Error building site: failed to load data: failed to load data: unmarshal failed: unexpected end of JSON input
```

**Comment by neflyte** [comment]
I've been using Hugo v0.101.0+extended and have had no issue. Perhaps try with a newer release?

**Comment by Harshil-Jani** [comment]
Tried with v0.101. and v0.104 Still facing same issue

**Comment by neflyte** [comment]
Hmm, this might be due to the JSON files extracted from code that get displayed in the docs. Try running `make dist` first to pull in the JSON data.

**Comment by neflyte** [comment]
@Harshil-Jani Did you have any luck running `make dist`?

**Comment by Harshil-Jani** [comment]
> @Harshil-Jani Did you have any luck running `make dist`?

Naah ! :(

**Comment by neflyte** [comment]
Could you reply with the output of running `make dist`? I'd like to confirm what the issue is.

**Comment by Harshil-Jani** [comment]
I extremly apologies for a really late reply, for some reasons the notification got skipped from my end and I almost forgot about it. 

 I figured it out now that the actual issue was with my `go` installation. And hugo was working as expected. Thankyou @neflyte for the follow up. I really appreciate that. Now, I can run docs on my local after fixing my `go` installation.
