### ISSUE TITLE
Plugin docs extractor is throwing errors

### ISSUE THREAD

**Issue by neflyte** [mattermost/mattermost-developer-documentation#1163]
It looks like there was a change in the mattermost-server repo recently that has caused the plugin docs extractor to throw non-fatal errors:

```
mkdir -p site/data
go run ./cmd/plugin-godocs > site/data/PluginGoDocs.json
go: downloading github.com/mattermost/mattermost-server/v6 v6.0.0-20220914120725-5d1fe271e68c
go run ./cmd/plugin-manifest-docs > site/data/PluginManifestDocs.json
2022/10/25 11:25:45 unrecognized types.Type: *types.Interface, any
2022/10/25 11:25:45 unrecognized types.Type: *types.Interface, any
```

I've got a card on my board to fix this: https://community.mattermost.com/boards/team/rcgiyftm7jyrxnma1osd8zswby/bbft5ccthufy1fcgdrz8ory7bga/vcfirybf6dtbu5b833e4dkhxt5a/ct4d1t4cpr38c5j4h6uyw7qrdxr

FYI that this issue exists :slightly_smiling_face:

**Comment by cwarnermm** [comment]
@neflyte - Would you like to leave this ticket with you, or reassign it?
