### ISSUE TITLE
Help Wanted: Validate dev docs README using Golang v.1.19

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/mattermost-developer-documentation#1201]
The developer documentation repository [README](https://github.com/mattermost/mattermost-developer-documentation/blob/master/README.md) lists a prerequisite of Golang v1.18+.

With the upgrade to [Golang v1.19](https://community.mattermost.com/core/pl/4674rsjbd3nbdphahhdwekirfe), validate the README content to ensure that the Mattermost developer documentation builds successfully using Golang v1.19.

**Comment by oraliahdz** [comment]
Hi, I can help with that. However, I see that currently the stable version si go1.20.1, should I use that one?

**Comment by oraliahdz** [comment]
This Issue was already solved in PR #1215
