### ISSUE TITLE
Search bar not displaying correctly in Firefox 109.0

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/mattermost-developer-documentation#1203]
When using Firefox 109.0 on macOS Ventura 13.1, the search bar isn't displaying correctly. Image provided is an example from https://developers.mattermost.com/integrate/marketplace-submissions/. A spot check confirmed that this is happening on all pages. 

![Screenshot 2023-01-26 at 19 28 32](https://user-images.githubusercontent.com/4223530/214906548-bb508238-ee5d-4dd9-94a3-2dbb4d086ae6.png)

**Comment by cwarnermm** [comment]
@emdecr - Are you open to investigating this issue further to understand and potentially fix root cause?

This may be reproducible on other browsers; however, I'm not seeing the same display issue using Microsoft Edge Version 109.0.1518.61 (Official build) (arm64).

**Comment by emdecr** [comment]
@cwarnermm Sure thing - great catch and should be an easy fix. Thanks!

**Comment by cwarnermm** [comment]
Thank you so much for your help with this, @emdecr! Please let me know where I can help if needed!
