### ISSUE TITLE
Help Wanted: Document usage of .nvmrc in plugin projects

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#1222]
Context of where this documentation be useful https://github.com/mattermost/mattermost-plugin-todo/issues/198#issuecomment-1441116706

Example
> You'll need to install node `14`, or install https://nvm.sh and run `nvm install` in the root of this repository

**Comment by mickmister** [comment]
@cwarnermm This issue is marked as completed, but I'm not sure if it ever was worked on

**Comment by imsherlocked** [comment]
@cwarnermm can I claim the issue and work on it?

**Comment by mickmister** [comment]
@imsherlocked Absolutely! Note that the general message to convey is:

> Different plugin projects may require specific versions of Node.js. The recommended version for the given project is always defined in a file in the root of the repository called `.nvmrc`. You can use the tool https://nvm.sh (Node Version Manager) to install and switch between node versions in your terminal. If you have `nvm` installed, you can run `nvm install` anywhere in the plugin repository, and it will automatically find the `.nvmrc` file in the root, and install and use that version. If you already have that version installed, you can run `nvm use`, though `nvm install` is easier since you don't need to check if you already have it installed.

**Comment by Rutam21** [comment]
@cwarnermm I would like to add this note and complete this ticket. Feel free to assign this to me.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!
