### ISSUE TITLE
Help Wanted: Add Gitpod docs link to server repo's README

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#1243]
https://developers.mattermost.com/contribute/more-info/getting-started/using-gitpod

The typical usage of Gitpod is to have an entrypoint in the README of a project. We have docs made to link to in the server repo, but we haven't added the link there.

There are a few options for presentation. Using links or certain images:

```
[Contribute with Gitpod](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

[![Small Image](https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod)](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

[![Large Image](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/mattermost/mattermost-server)
```

Which renders as:

[Contribute with Gitpod](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

[![Small Image](https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod)](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

[![Large Image](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

---

Some additional related items:

- I think we should update Gitpod docs to emphasize the entrypoint in the server repo rather than https://github.com/mattermost/mattermost-gitpod-config, since we will have a different primary entrypoint to Gitpod
- https://github.com/mattermost/mattermost-developer-documentation/issues/1244
- https://github.com/mattermost/mattermost-developer-documentation/issues/1245

**Comment by mickmister** [comment]
cc @azigler for visibility

**Comment by mickmister** [comment]
Also cc @cwarnermm @justinegeffen 🙂

**Comment by justinegeffen** [comment]
Thanks, @mickmister! What is the turnaround required for this?

**Comment by mickmister** [comment]
@justinegeffen No urgency at all on this. Technically doesn't ever _need_ to be done but I want to capitalize on the efforts we have for documenting how to use Gitpod. Also, I'd say discussion of how this should be done is the first step. _Where_ in the README and what to use as presentation as mentioned in the ticket description.

**Comment by mickmister** [comment]
@cwarnermm I'm wondering your thoughts on this ticket, particularly what rendering style mentioned in the description we should use

**Comment by cwarnermm** [comment]
@mickmister - The second option provided feels like a good fit, particular when contrasted to our own plugin README pages: 

[![Small Image](https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod)](https://gitpod.io/#https://github.com/mattermost/mattermost-server)

Do you have bandwidth to make these updates, @mickmister?

**Comment by aniketh-varma** [comment]
Hi @cwarnermm, I would like to work on this issue.

**Comment by mickmister** [comment]
Awesome! Thanks @aniketh-varma!
