### ISSUE TITLE
Help Wanted: OpenSSL 3.0 legacy provider note

### ISSUE THREAD

**Issue by jacob-morin** [mattermost/mattermost-developer-documentation#1281]
Hi all, 

As of OpenSSL 3.0, some algorithms (in this case specifically, RC2) have been moved to the `legacy` provider, which is not loaded by default (see https://wiki.openssl.org/index.php/OpenSSL_3.0). This causes the command `openssl pkcs12 -in Certificates.p12 -out aps_production_priv.pem -nodes -clcerts -passin pass:` on line 92 of `site/content/contribute/more-info/mobile/push-notifications/service.md` to fail with the cryptic error: 
```
Error outputting keys and certificates
00E68F1701000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

I got around this issue by adding the `-legacy` option to my command, which loads the legacy provider (and therefore the RC2 algorithm). Perhaps this is worth noting in the documentation?

**Comment by Omar8345** [comment]
Can I get assigned to this?

**Comment by cwarnermm** [comment]
Thank you, @Omar8345, for your help with this issue!
