### ISSUE TITLE
Optimize development environment setup document

### ISSUE THREAD

**Issue by egege** [mattermost/mattermost-developer-documentation#1282]
When using the Mac ARM chip, it is necessary to install Rosetta in order to ensure successful deployment. Not all underlying libraries of libpng are compatible with ARM.

I encountered issues during my previous deployment and resolved them by installing Rosetta.
[mattermost 8.0.0 make run error](https://github.com/mattermost/mattermost/issues/24120)

**Comment by harshilsharma63** [comment]
Docs PR created - https://github.com/mattermost/mattermost-developer-documentation/pull/1283
