### ISSUE TITLE
"Contribute" and "Integrate & Extend" Section Content Alignment Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [mattermost/mattermost-developer-documentation#1302]
The current design of the home page is impressive but it can be improved by working on the alignment of the content of "Contribute" and "Integrate & Extend" section. Aligning them in center will improve user focus on these sections content and overall design of homepage.

## Screenshots

**Current Design**

![img (1)](https://github.com/mattermost/mattermost-developer-documentation/assets/115794049/ba2c0ea3-3498-4659-9025-430ec1179d9a)

**Expected Updated Design**

![img (2)](https://github.com/mattermost/mattermost-developer-documentation/assets/115794049/154a67b2-a7a4-40c6-a2d5-eb4470210281)

**Comment by cwarnermm** [comment]
Thank you, @iamRabia-N! Are you open to creating a dev docs PR to implement your excellent suggestion?

**Comment by iamRabia-N** [comment]
Yes. Assign me this issue.
