### ISSUE TITLE
Help Wanted: Correct Attachments documentation

### ISSUE THREAD

**Issue by Michael1248** [mattermost/mattermost-developer-documentation#1309]
on page https://developers.mattermost.com/integrate/reference/message-attachments/#can-i-send-a-message-attachment-via-the-api
the explanation does not work for me. The attatchments field has to be on top level. not in props. see also https://developers.mattermost.com/integrate/webhooks/incoming/#parameters where it seems to be documented correctly

**Comment by cwarnermm** [comment]
Thanks, @Michael1248! Are you open to creating a dev docs PR with your proposed changes? We welcome your contribution!

**Comment by Omar8345** [comment]
Can I be assigned for this?

**Comment by Omar8345** [comment]
Hi @cwarnermm!

Could I be assigned on this task?

Thanks!
