### ISSUE TITLE
Interactive Dialog Docs: Remove mention of nonexistent limit of dialog elements

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#1339]
Regarding [Interactive Dialogs](https://developers.mattermost.com/integrate/plugins/interactive-dialogs/), the docs say that we can only use up to 5 elements in a dialog, but clearly the demo plugin way more. I can't see any limit being imposed in the code as well.

The task here is to update the documentation for this page to remove the mention of the limit of elements
https://developers.mattermost.com/integrate/plugins/interactive-dialogs

_Issue created from a [Mattermost message](https://hub.mattermost.com/_redirect/pl/uqga3rwqcjyxuc3juiceukxuww) *by @harshilsharma63*._

**Comment by vishal-rathod-07** [comment]
@mickmister I would like to work on this can you assign this to me.

**Comment by mickmister** [comment]
Thank you @vishal-rathod-07!
