### ISSUE TITLE
Instruction for stopping docker container is given in developing Mattermost without docker documentation

### ISSUE THREAD

**Issue by chessmadridista** [mattermost/mattermost-developer-documentation#1378]
# What is the issue?
In the section titled "Develop Mattermost without Docker" on [this link](https://developers.mattermost.com/contribute/developer-setup/#develop-mattermost-without-docker:~:text=the%20running%20docker%20containers%3A-,make%20stop%2Ddocker,-Set%20your%20options%3A%20Some), the code for stopping docker container is given.

If we are developing Mattermost without Docker, is there any need for that code snippet?

# Proposed solution

> The stop-server make target does not stop all the docker containers started by run-server. To stop the running docker containers:
> 
> ```
> make stop-docker
> ```
> 

This whole section can be removed for better readability.

**Comment by chessmadridista** [comment]
I would be happy to take up this issue if it is something that needs to be resolved.

**Comment by cwarnermm** [comment]
Thank you, @chessmadridista!
