### ISSUE TITLE
`docs` folder is not in `.gitignore`

### ISSUE THREAD

**Issue by chessmadridista** [mattermost/mattermost-developer-documentation#1379]
# What is the issue?
The `docs` folder gets created when `make run` command is executed in the terminal. When I do `git status`, it shows `docs` folder as untracked.

It is not included in `.gitignore`.

Here is a screenshot of the same.

![Screenshot from 2024-06-10 22-59-31](https://github.com/mattermost/mattermost-developer-documentation/assets/58620639/7727ba7b-0dcc-493e-bc84-db2d4c6d29ea)

# Proposed solution
The `docs` folder should be included in `.gitignore`.

**Comment by chessmadridista** [comment]
I will be happy to take up this issue. 

Please let me know in case something is amiss in my understanding and there is a reason why it is not included in `.gitignore`.

**Comment by cwarnermm** [comment]
The `make run` command doesn't currently output files to the same directory as the `make build` command. This is a known issue of low priority that doesn't impact generated docs output. I'd prefer to address an issue like this by updating the `makefile` to ensure output is in the correct directories. Let me know if you're open to investigating the changes needed to the `makefile`.

**Comment by chessmadridista** [comment]
> The `make run` command doesn't currently output files to the same directory as the `make build` command. This is a known issue of low priority that doesn't impact generated docs output. I'd prefer to address an issue like this by updating the `makefile` to ensure output is in the correct directories. Let me know if you're open to investigating the changes needed to the `makefile`.

I have a couple of questions:
1. > ...ensure output is in the correct directories...
So should the docs folder be created inside the `dist` directory when `make run` is executed? Or in some other directory?
2. Do `docs` and `dist` folder serve different purposes?
3. What is the harm in adding `docs` folder to `.gitignore` if it is used only for development purposes?
4. What benefits do we get if we don't add `docs` folder to `.gitignore`?

# New solution
In [config.toml file](https://github.com/mattermost/mattermost-developer-documentation/blob/5d97341b14c5e525b682ff15d2289e98a62a5e34/site/config.toml#L8C1-L9C1), I just need to change the path in line \#8:
`publishDir = "${new_path}"`
Here new_path is the placeholder. Once I know the exact path, I will replace it here.

**Comment by cwarnermm** [comment]
@chessmadridista - As I mentioned, this is a low priority issue that doesn't impact the production instance of the Mattermost Developer Documentation, nor does it impact generated docs output. The Mattermost Docs team doesn't have bandwidth to take on an investigation in this area at this time. That being said, you're always welcome to dig deeper to find answers to your questions and help propose a future iteration of cleanup for this repository.

Perhaps there are ways to achieve similar directly within your local dev environment that don't involve changes to this Mattermost repository.

**Comment by chessmadridista** [comment]
Hi @cwarnermm, thank you for the detailed clarification!

Sure, I will create a PR having the `docs` folder in `.gitignore`.

Shall I create another issue for finding out the root cause of why the files are being made in `docs` folder instead of the `dist` folder when `make run` is executed?

**Comment by cwarnermm** [comment]
That would be really great, @chessmadridista! Thank you!

**Comment by chessmadridista** [comment]
> That would be really great, @chessmadridista! Thank you!

Hi @cwarnermm, I am happy to be of help!

#1383 has been created to investigate the `Makefile` issue related to `docs` and `dist`.
