### ISSUE TITLE
There is no mentioning of the PORT at which the webapp runs in the documentation

### ISSUE THREAD

**Issue by X1Vi** [mattermost/mattermost-developer-documentation#1421]
#### Summary
In the [setup environment documentation](https://developers.mattermost.com/contribute/developer-setup/) there is no mention of the PORT of the which webapp runs in. User can see it by going inside the code but that is not the intended behavior.
The documentation exists to make it easier for new contributors to contribute

#### Steps to reproduce
Go to the [setup environment documentation](https://developers.mattermost.com/contribute/developer-setup/)  and look at the flow setup with "Setup the Mattermost Server"

#### Operating System
N/A

#### Mattermost Server Version
N/A

#### Expected behavior
The PORT for the webapp must be told in the documentation itself

#### Observed behavior
The PORT in the documentation is not there.

#### Log Output
N/A

#### Additional Information
N/A

#### Possible fixes
Mention the PORT for the webapp in the documentation

**Comment by cwarnermm** [comment]
Addressed via https://github.com/mattermost/mattermost-developer-documentation/pull/1423
