### ISSUE TITLE
Integrate section: high level design

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-developer-documentation#15]
High level design.

- [x] Getting Started
    - [x] How Should I Integrate?
- [x] Incoming Webhooks
    - [x] Usage
    - [ ] Example
- [x] Outgoing Webhooks
    - [x] Usage
    - [ ] Example
- [x] Slash Commands
    - [x] Usage
    - [ ] Example
- [ ] Message Attachments
    - [ ] Interactive Message Buttons
    - [ ] Message Builder - similar to https://api.slack.com/docs/messages/builder
- [ ] REST API
    - [ ] Usage
    - [ ] API Reference - link out to api.mattermost.com
    - [ ] Personal Access Tokens
    - [ ] Example - probably CH's bot sample
- [ ] OAuth 2.0
    - [ ] Example - probably EN's oauth sample

**Comment by ccbrown** [comment]
I wonder if interactive message buttons should be a subsection of message attachments.

Would definitely be nice to have a message builder in here somewhere: https://api.slack.com/docs/messages/builder

**Comment by jwilander** [comment]
Good point, updated
