### ISSUE TITLE
Add dep ensure before starting mattemost server

### ISSUE THREAD

**Issue by walidsebai** [mattermost/mattermost-developer-documentation#176]
it seems that we must use `dep ensure` before `make run` to start mattermost server, other way it tell me a package is missing.
actual error:
`cmd/mattermost/main.go:9:2: cannot find package "github.com/mattermost/mattermost-server
/cmd/mattermost/commands" in any of:
       /home/wsebai/go/src/mattermost-server/vendor/github.com/mattermost/mattermost-server/cmd/mattermost/commands (vendor tree)
        /usr/lib/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands (from $GOROOT)
         /home/wsebai/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands (from $GOPATH)

cmd/mattermost/main.go:15:2: cannot find package "github.com/mattermost/mattermost-server/imports" in any of:
	/home/wsebai/go/src/mattermost-server/vendor/github.com/mattermost/mattermost-server/imports (vendor tree)
	/usr/lib/go/src/github.com/mattermost/mattermost-server/imports (from $GOROOT)
	/home/wsebai/go/src/github.com/mattermost/mattermost-server/imports (from $GOPATH)

cmd/mattermost/main.go:12:2: cannot find package "github.com/mattermost/mattermost-server/model/gitlab" in any of:
	/home/wsebai/go/src/mattermost-server/vendor/github.com/mattermost/mattermost-server/model/gitlab (vendor tree)
	/usr/lib/go/src/github.com/mattermost/mattermost-server/model/gitlab (from $GOROOT)
	/home/wsebai/go/src/github.com/mattermost/mattermost-server/model/gitlab (from $GOPATH)
`

**Comment by lieut-data** [comment]
Hey @walidsebai, thanks for relocating the original [issue](https://github.com/mattermost/docs/issues/2336) and posting the detailed error.

Something doesn't seem right in the errors above: `github.com/mattermost/mattermost-server
/cmd/mattermost/commands` is part of the repository in question, so it would never be part of `vendor/` in the first place, and thus not affected by `dep ensure`.

Did you follow https://developers.mattermost.com/contribute/server/developer-setup/ to setup your environment? Can you describe any extra steps you took that led to this error?

**Comment by walidsebai** [comment]
yes i did follow , maybe i did the `Edit /etc/security/limits.conf` the last thing but don't thing that would affect the setup. i think it would be better if we recreate it ?

**Comment by walidsebai** [comment]
i think i understand the problem, it's my fault i downloaded the source code in go/src/ so yeah u are right sorry for the inconvenience, i'm closing this now.
