### ISSUE TITLE
Server Plugin Developer Workflow - Document rebuild and redeploy steps.

### ISSUE THREAD

**Issue by sadohert** [mattermost/mattermost-developer-documentation#231]
It would be helpful to have some steps for making code changes, rebuilding, and redeploying server plugins for testing at the bottom of https://github.com/mattermost/mattermost-developer-documentation/blob/master/site/content/extend/plugins/server/hello-world.md#installing-the-plugin.

What's the most efficient approach?  Right now I disable the plugin in the Management Console, then:
```
<plugin dir> $ make deploy # this directory is parallel to the mattermost-server directory
```

Then I re-enable the plugin and I see my updates.  Is this the most efficient way?

Happy to type up the PR if someone can confirm the steps.

Thanks!

**Comment by hanzei** [comment]
Hey @sadohert,

The most efficient approach is to run just `make deploy`. It takes care of removing the old plugin and enables the new installed version. No further steps are needed.

The site you linked is a generic introduction into plugins. `make deploy` is only available on plugins which use the [Sample Plugin template](https://github.com/mattermost/mattermost-plugin-sample/). Hence I would much rather improve the readme on https://github.com/mattermost/mattermost-plugin-sample/.

What do you think about this?

**Comment by sadohert** [comment]
Ahhh yes.   I wasn't thinking about the `make deploy` being a plugin project-specific thing.  So yes, probably makes sense to improve the readme.

But even within the context of someone building a plugin with their own build scripts, are you saying we should be able to just replace the plugin binary and the server will pick this up and start using it?  For me, I:
* cloned the plugin-sample,
* edited the [hello world](https://github.com/mattermost/mattermost-plugin-sample/blob/ff7758dc6ac9f041ea3d5921cdd9faadc2c987a6/server/plugin.go#L23) print statement with a new string, 
* rebuilt with `make deploy`, and then 
* refreshed `http://<myserver>/plugins/<my cloned plugin>` 

... and I don't see the changed string (e.g., "Hello World 2").  I checked the timestamp of the plugin binary file on the server and it's updated.   Only way I'm able to get the plugin behaviour to change (i.e., print my new string) is to disable and re-enable the plugin.

Maybe something else I'm doing wrong?

My setup follows [these server development instructions](https://developers.mattermost.com/contribute/server/developer-setup/).

Incidentally, in previous testing I noticed that `make stop-server` wasn't actually killing the process for the 2 plugins I have installed (mattermost-plugin-sample, and mattermost-plugin-demo).  I had to manually kill them.... discussed this with @lieut-data  and was going to submit a separate report for that.

**Comment by sadohert** [comment]
Thanks @levb .... I'll close this issue.  Ultimately I wanted to understand the "developer workflow" for `code > build > deploy > test > repeat`.  I wasn't finding repeating the steps in the server/plugin docs was resulting in a sane workflow (seemed like I was having to restart the server and `kill` plugins to see updated behaviour)... BUT, after:

1) Updating my server to the latest,
2) Removing the [mattermost-demo-plugin](https://github.com/mattermost/mattermost-plugin-demo) from my local setup (this still doesn't seem to clean up properly on `make stop-server`, I'll submit somethign separate),
3) Setting up these environment variables:
```
export MM_SERVICESETTINGS_SITEURL=http://localhost:8065
export MM_ADMIN_USERNAME=<admin account>
export MM_ADMIN_PASSWORD=<admin password>
```
I can successfully `code > build > deploy > test > repeat` without server restarts or killing plugins.

Thanks

**Comment by hanzei** [comment]
Thank you very much for your feedback @sadohert!
