### ISSUE TITLE
Numbered list unexpectedly restarts in /internal/writing-a-blog-post/

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-developer-documentation#234]
Repro:

1. Go to https://developers.mattermost.com/internal/writing-a-blog-post/
2. Read the doc, and notice that the numbered list restarts at 1 after the code block

![image](https://user-images.githubusercontent.com/13119842/52484062-68c59480-2b83-11e9-987b-3b76c7c27304.png)

This is even though the GitHub .md file has the correct numbered list

https://github.com/mattermost/mattermost-developer-documentation/edit/master/site/content/internal/writing-a-blog-post.md

**Comment by jwilander** [comment]
Probably just need to tab in the code block

**Comment by jasonblais** [comment]
Trying that https://github.com/mattermost/mattermost-developer-documentation/pull/235

**Comment by jasonblais** [comment]
Thanks Joram! Resolved by https://github.com/mattermost/mattermost-developer-documentation/pull/235
