### ISSUE TITLE
Provide response payload example for submission of Interactive Dialog

### ISSUE THREAD

**Issue by JAGFin1** [mattermost/mattermost-developer-documentation#250]
Humble apologies if this has previously been covered, or if I've missed it, but the documentation for how to handle responding to an Interactive Dialog submission appears to be a bit unclear. 

**Page**: https://docs.mattermost.com/developer/interactive-dialogs.html

The text states:

> Finally, once the request is submitted, we recommend the integration to respond with a system message or an ephemeral message confirming the submission.

However it is not clear on how to structure this response. I have made attempts to respond with a payload akin to a standard Slash Command response, as well as that for an Interactive Message response. While it is likely that I have simply configured my code incorrectly, I believe having a hard example of how to respond to a Dialog submission would help users, especially as all other submissions and responses on the above documentation page come with payload examples.

**Comment by hanzei** [comment]
Hey @JAGFin1,

Right now there is no way to directly send an ephemeral message within the dialog submit response. But you can use the [REST API to do so](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts~1ephemeral%2Fpost). Or the plugins API if you are developing a plugin.

On the other hand I see the need of having the possibility build into the response.

@jasonblais Thoughts on adding something like `EphemeralText` to `SubmitDialogResponse`?

**Comment by jasonblais** [comment]
@hanzei 0/5, but I think @JAGFin1 is asking for a concrete example of how to respond to a Dialog submission. Is this something you'd be open to helping with, or should we queue this for engineers to help with?

**Comment by hanzei** [comment]
A basic example would be:

```go
response := &model.SubmitDialogResponse{
			Errors: map[string]string{
				someKey: "Some erro",
			},
}
w.Header().Set("Content-Type", "application/json")
w.WriteHeader(http.StatusOK)
_, _ = w.Write(response.ToJson())
```

inside your http server that handles the submit dialog request. This would show an error for the element with the key `someKey`.

@JAGFin1 Are you using a plugin or the REST API to open the dialog? If you want, I can share an example on how to send an ephemeral message.

**Comment by JAGFin1** [comment]
Hi @hanzei,

I'm using the REST API to open the dialog. That's working as intended. The specific issue is when the user submits the dialog (and thus performs a request back to my service), I do not know what the HTTP response should contain in order for Mattermost to display a message as a "Your submission has been logged" type of message. 

That being said, I believe I may have misunderstood the original documentation. Based on what you said, it looks like I need to send a separate request back to Mattermost once my service has received (and responded to) a submission request from a dialog. This differs from how errors are handled as they are returned directly in the response.

Is that correct? If so, I can manage that.

**Comment by hanzei** [comment]
That is correct @JAGFin1.

@jasonblais what do you think about clarifying this in the docs?

**Comment by jasonblais** [comment]
Certainly, does this document update capture it?

https://github.com/mattermost/docs/pull/2592

**Comment by JAGFin1** [comment]
Thanks for the clarification @hanzei and @jasonblais. The amendment to the documentation has made it clearer about what the integration needs to do. If possible, a JSON example for the HTTP API (and endpoint) or a reference to the `/posts/ephemeral` documentation would be perfect.

**Comment by hanzei** [comment]
Thanks for your suggestion @JAGFin1. :+1:  I opened a PR to add a code sample to the API documentation.

Closing this one.
