### ISSUE TITLE
windows dev setup recommends install of babun

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-developer-documentation#256]
step 6 recommends installing babun which is officially discontinued as of january this year

an alternative should be found somehow. like mingw or cygwin or something like that.

**Comment by svelle** [comment]
I'm currently working on getting a proper setup to run maybe I can fix the docs then. But I'm happy for anybody else who wants to help out

**Comment by cpoile** [comment]
I don't run windows... But docksal has an issue like this as well, and I think they're moving to just using WSL: https://github.com/docksal/docksal/issues/1004

**Comment by svelle** [comment]
that's not a bad idea at all. I just use the git bash that's installed with git for windows but using WSL could work too

**Comment by QueenMarisWang** [comment]
curl http://localhost:8065/api/v4/system/ping                                                                                                    /cygdrive/c/Go/src/github.com/mattermost/mattermost-server
curl: (7) Failed to connect to localhost port 8065: Connection timed out


how should i solve this?thx

**Comment by singh-sarabjeet** [comment]
I'm gonna do a setup on my windows machine and check if WSL works fine for the setup. @jespino Can you assign this issue to me? I'll raise a PR to update the docs accordingly.

**Comment by singh-sarabjeet** [comment]
Alternatively, I'm thinking should we remove the Windows tab completely since we already have a setup documentation for Windows WSL? @svelle

**Comment by svelle** [comment]
> Alternatively, I'm thinking should we remove the Windows tab completely since we already have a setup documentation for Windows WSL? @svelle

good point @singh-sarabjeet at the time of opening the issue the WSL section wasn't available yet so I'd be good with removing that section. However I'm not part of the dev team this is not my decision to make so I'd wait for feedback from @jespino and other folks from engineering.

**Comment by singh-sarabjeet** [comment]
@svelle Sounds good. In the meantime can you assign this issue to me?

**Comment by jespino** [comment]
@singh-sarabjeet assigned to you, I'm not very familiarized with the windows environment, maybe @hmhealey have an strong opinion here.

**Comment by singh-sarabjeet** [comment]
Will wait for reply from @hmhealey . Also, @svelle was there a JIRA ticket associated with this?

**Comment by hmhealey** [comment]
That would probably make sense. I haven't developed MM on Windows myself, but I know of a few people on the team who use WSL primarily, so those instructions should be stable enough.

**Comment by singh-sarabjeet** [comment]
Please check and approve the PR. I also realised there are no instructions for windows setup for Mattermost documentation. I had to engineer my way by using WSL to install make, homebrew and then Hugo. I think these steps are required on README. @svelle can you create an issue for that or maybe I can report it.
