### ISSUE TITLE
Need a documentation style guide

### ISSUE THREAD

**Issue by Rajakavitha1** [mattermost/mattermost-developer-documentation#330]
We do have a great style guide for code: https://docs.mattermost.com/developer/style-guide.html
However, we dont seem to have any guidelines for writing content, in other words, a documentation style guide. A documentation style guide is critical to ensure that the format, content, word usage, typographic conventions, and language is consistent across the document.

**Comment by justinegeffen** [comment]
Hi @Rajakavitha1. Thanks for raising this. We do have a Documentation Style Guide located here: https://docs.mattermost.com/guides/core.html#documentation-style-guide. Is that more along the lines of what you're looking for? If you have any suggestions for improving the guide, that'd be great.

**Comment by Rajakavitha1** [comment]
Hi @justinegeffen Thanks for the link. This is exactly what I was looking for.
