### ISSUE TITLE
Help Wanted: Update push proxy setup with docs for systemd distros

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-developer-documentation#332]
the current docuementation [here](https://developers.mattermost.com/contribute/mobile/push-notifications/service/) is probably written with ubuntu 16.04 in mind which still used upstart. doing the steps on 18.04 won't work since it's using systemd.

the docs need to be updated to reflect those changes since this will also not work on newer rhel releases and 16.04 will be EOL in 2020.

Elias also pointed out that it might be better to make the docs system agnostic and not show include any particular step by step solution for the system files but rather point in the right direction, which would prevent situations like this in the future.

**Comment by cwarnermm** [comment]
Deploy docs are now platform-specific. Closing.
