### ISSUE TITLE
Update cherry pick process

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-developer-documentation#347]
With the new automated cherry picks, the documentation needs an update:
- https://developers.mattermost.com/contribute/getting-started/branching/#cherry-pick-process-developer
- https://developers.mattermost.com/contribute/getting-started/code-review/

Also the label list needs an update.

**Comment by hanzei** [comment]
@cpanato Would you take care of this?

**Comment by cpanato** [comment]
i can add in my backlog, low priority

**Comment by cpanato** [comment]
@hanzei i guess you did that, right?

**Comment by hanzei** [comment]
Not really. These two pages still need an update.
