### ISSUE TITLE
Help Wanted: When Selecting a Tab From The LHS, The Parent Tab Collapses

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-developer-documentation#348]
### Context 
When selecting a child tab of a parent tab that only contains single-leveled children, the tab stays open and highlighted. Example: `Web App > Developer Apps`

Selecting any tab should update the RHS content window and the newly clicked tab should remain highlighted.  Also, the parent should not collapse.

However, when selecting a child tab of a parent tab that contains multi-leveled children, clicking the child tab collapses its parent tab. Example: `Mobile Apps > Developer Setup > Mobile Apps Workflow`

![recording](https://user-images.githubusercontent.com/7575921/63627934-9037f800-c5cf-11e9-9940-a9a0d8f0a8e7.gif)

## Docs request

Investigate whether this is something configurable via Hugo (the tooling that generates the HTML developer documentation). If it is configurable, submit a dev docs PR that incorporates this configuration.

## How you can help

Determine whether this user experience is something we can achieve using the existing dev docs tool chain in place. We don't have the answer to this question yet ourselves, so we're not able to provide much direction on how to get started.

**Comment by cwarnermm** [comment]
Confirmed that this issue is present in production today.

**Comment by cwarnermm** [comment]
@neflyte - Is this something configurable and under our control via Hugo?
