### ISSUE TITLE
Good code review ideas

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#358]
Mattermost user `joram` from https://community-release.mattermost.com has requested the following be documented:

```
https://google.github.io/eng-practices/review/reviewer/

There are some very good point that I could see us adopting into our culture. Maybe we could extract certain points into a new document on the developers page?
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/ixdjfhbxhjdqjbj93m5x9g1zdo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by hanzei** [comment]
Making this a help wanted. If someone want to make a proposal, let me please know.

**Comment by hanzei** [comment]
Making this a help wanted. If someone want to make a proposal, let me please know.

**Comment by cwarnermm** [comment]
@jwilander - Following up on this ticket with you to see whether this work was completed.

**Comment by jwilander** [comment]
Closing. If someone sees something in there that would make a good addition to our docs we would definitely accept a proposal in the form of a PR.
