### ISSUE TITLE
Updating stores requires running `make store-layers` in addition to `make store-mocks` now

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#362]
Mattermost user `joram` from https://community-daily.mattermost.com has requested the following be documented:

```
#### #AUG07 4) PSA: TimerLayer on master and the need of `make store-layers` on store API changes
I merged into master the automatically generated TimerLayer, which means that now, every change to the store needs to execute the `make store-mocks` and `make store-layers`. By the way, if somebody have any idea of layers that wants to add the store and can be autogenerated, let me know and we can think if makes sense.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/rfbn96eotiyjznunf4cur3auth).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@jwilander - Was this update applied to the product documentation?
