### ISSUE TITLE
Move Plugins on Community Server into internal section

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-developer-documentation#365]
I not a topic that is important to the public. My proposal is to move it into the internal section.

@levb @lieut-data Objections?

**Comment by cpanato** [comment]
if moving to a internal documentation, please move to this: https://github.com/mattermost/internal-docs
/cc @DSchalla

**Comment by lieut-data** [comment]
No objections. This information might naturally surface if we expose the marketplace to non-system administrators anyway.

**Comment by hanzei** [comment]
> No objections. This information might naturally surface if we expose the marketplace to non-system administrators anyway.

I'm confused. Carlos proposed to move it into a _private_ repo. Are you fine with that?

Or is this page outdated anyway and we should just rely on the marketplace?

**Comment by lieut-data** [comment]
Hmm. I'm inclined to think the information will always be outdated, and we can just rely on the marketplace as such (eventually). @levb, any concerns with just dropping this section on mattermost.dev instead?

**Comment by levb** [comment]
No objections at all

**Comment by hanzei** [comment]
@cpanato @DSchalla What is the reason this should be in a private repo? The information is not sensitive IMO, just unnecessary for the public.

**Comment by DSchalla** [comment]
@hanzei While this information may not be sensitive, there is other information which is. Since this information has no use to the public, moving it to the dedicated internal documentation repository may make sense.

In this specific case I don't have a strong opinion on it however.

**Comment by cpanato** [comment]
@hanzei @DSchalla agree with Daniel, also this documentation the public will not get any benefit with.

**Comment by hanzei** [comment]
After reconsidering I think there **is** value in this being plugin. It encourages plugin devs to push there plugins to the community server. Let's leave it as it is, if no one has strong objections.
