### ISSUE TITLE
Get rid of GOPATH in the developers setup guide

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-developer-documentation#380]
Given we are now 100% using the local vendor folder with go modules, there is no need clone the repo inside `GOPATH` any longer. We should remove this from our setup guide.

Keep in mind that the server and webapp directories still have to be in the same directory so our `Makefile` can find them.

**Comment by jorgeruvalcaba** [comment]
Can I work on this issue?

**Comment by hanzei** [comment]
Sure, that would be awesome @jorgeruvalcaba  :tada:

**Comment by jorgeruvalcaba** [comment]
Added a PR for this issue, thanks @hanzei
