### ISSUE TITLE
Request for Documentation: Das ist eine Doku

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#398]
Mattermost user `der_test` from https://community.mattermost.com has requested the following be documented:

```
Hi, I am a Java developer from Manila, Philippines. I wish to help translate to Filipino language.  
```

See the original post [here](https://community.mattermost.com/_redirect/pl/3rw1ojgc3idi9eo5coaxpth3qa).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by hanzei** [comment]
Closing this as invalid.
