### ISSUE TITLE
UPDATING DOCUMENTATION: Fixing broken links related to Contribution Guidelines

### ISSUE THREAD

**Issue by DaKeiser** [mattermost/mattermost-developer-documentation#399]
###### Description
In [`developer-workflow.md`](https://github.com/mattermost/mattermost-developer-documentation/blob/master/site/content/contribute/server/developer-workflow.md) there are a few links like [this](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request), which I believe to my knowledge are broken. 

###### Suggestions for improvement
On researching I did find a [link](https://jeffschering.github.io/mmdocs/upgrade/developer/contribution-guide.html) which I believe existed earlier, but does not exist currently. 

###### How to fix it
I believe we must update the documentation by changing it from https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request to https://developers.mattermost.com/contribute/getting-started/ to maintain the homogeneity in our docs.

**Comment by DaKeiser** [comment]
@hanzei thanks for assigning, fixed this issue in PR #400

**Comment by DaKeiser** [comment]
@hanzei I unassigned myself by mistake. No hard feeluings XD

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-developer-documentation/pull/410
