### ISSUE TITLE
Need better way to commit build

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-developer-documentation#4]
Right now you need to run `hugo` in the `/site` directory which will dump the built site into `/docs` which is pretty messy and will likely make rebasing a pain.

**Comment by ccbrown** [comment]
I think this'll be solved by https://github.com/mattermost/mattermost-developer-documentation/issues/10, since once we do that, we won't need to actually commit the built site.

In the meantime, hopefully we don't have too much trouble with it while it's just us and merge contention is low.

**Comment by jwilander** [comment]
Yeah, sounds good
