### ISSUE TITLE
UPDATING DOCUMENTATION: Fixing broken links related to REST API

### ISSUE THREAD

**Issue by DaKeiser** [mattermost/mattermost-developer-documentation#401]
###### Description
In [`REST API`](https://developers.mattermost.com/contribute/server/rest-api/) there are a few links like [this](https://docs.mattermost.com/developer/dev-setup.html) and [this](https://docs.mattermost.com/developer/api4.html#writing-a-unit-test) in `Implementing the API handler` title, which I believe to my knowledge are broken. 

###### How to fix it
I believe we must update the documentation by changing 
- https://docs.mattermost.com/developer/dev-setup.html to https://developers.mattermost.com/contribute/server/developer-setup/
- https://docs.mattermost.com/developer/api4.html#writing-a-unit-test needs to have a proper documentation, as following the links leads to the same site https://developers.mattermost.com/contribute/server/rest-api/ . An appropriate site for the same could be helpful

I believe updating them would be useful.

**Comment by DaKeiser** [comment]
And I'm really sorry, as this is the same kind of issue I had raise yesterday too. As far as I know, these are the final links which are broken.

**Comment by Rajakavitha1** [comment]
Hi @DaKeiser ! This is now fixed in the PR https://github.com/mattermost/mattermost-developer-documentation/pull/409
