### ISSUE TITLE
Request for Documentation: How to run with dev environment without Docker

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#404]
Mattermost user `joram` from https://community-release.mattermost.com has requested the following be documented:

```
I'm not sure we have documentation yet, but there is a `MM_NO_DOCKER` setting you can use to disable docker compose and just run the database yourself if you prefer.

Can you share context into the difficulties leading you to avoid Docker in this context?
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/xgnbdt9ejjfqjn18swubguor1c).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@jwilander @coltoneshaw  - From your perspectives, is this ticket still valid and something we should action in the developer documentation?
