### ISSUE TITLE
Request for Documentation: Mattermost as a OAuth 2.0 Service Provider - Supported Grant Flows and URLs

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#415]
Mattermost user `joram` from https://community-release.mattermost.com has requested the following be documented:

```
We support the [authorization code](https://oauth.net/2/grant-types/authorization-code/) and [implicit](https://oauth.net/2/grant-types/implicit/) grant flows for OAuth 2.0 applications. The authorize URL is `<your-mattermost-url>/oauth/authorize` and the token URL is `<your-mattermost-url>/oauth/access_token`
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/5jp94uyo8f8ftjk4w6qqz11yyc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@jwilander - This ticket has been idle for some time. Would you or a member of your team be open to creating a PR with the requested documentation updates?

**Comment by jwilander** [comment]
I can submit it
