### ISSUE TITLE
Request for Documentation: [Desktop] Document config.json file parameters along with validation requirements

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#429]
Mattermost user `deanwhillier` from https://community-release.mattermost.com has requested the following be documented:

```
Hi @epuentes, @jthebab is correct, with version 4.2.2, we added externally loaded file validation as part of a security hardening effort.

The desktop app now expects the `config.json` to include all the properties defined in the `defaultPreference.js` file found here: https://github.com/mattermost/desktop/blob/master/src/common/config/defaultPreferences.js as that file is used to generate a new `config.json` file when one doesn't exist.

If you update your version above to include the additional missing parameters from the `defaultPreference.js` file, it should work.

Hope that helps!
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/wcy4jcrrufgz7pjftu4kt1ay3r).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by bvineyar** [comment]
I am updating https://github.com/mattermost/docs/edit/master/source/deployment/desktop-app-deployment.rst with this new information, and also updating with text for the latest version 4.3.1.
