### ISSUE TITLE
Help Wanted: How do you test server-side telemetry?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#444]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
When resolving a Jira ticket or testing your changes, use the following steps. 

NOTE: These steps are a sample for https://mattermost.atlassian.net/browse/MM-19171, but should be generalized for final docs

1. Configure ES in a Mattermost server
2. Enable "Error and Diagnostics Reporting" in "System Console > Logging"
3. 24 hours later, confirm in Segment that `<field>` `<value>` is sent to `<table>` for that server. (Config settings are sent back to Segment every 24 hours, hence why the 24-hour wait time)

Make sure to include the exact information that is being sent to Segment in the QA test steps (including which table, field, and values).

For more information on telemetry, see https://docs.mattermost.com/administration/telemetry.html
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/9w513y6afpdtpmp66tj5um76ww).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@saturninoabril - Is this something that the QA team could take on as part of monthly development docs maintenance?

**Comment by saturninoabril** [comment]
Thanks for the ping @cwarnermm! I don't think this is still applicable as we're no longer relying on Segment. However, even with the current setup of sending telemetry to RudderStack (with https://pdat.matterlytics.com), I would not recommend in adding this tedious manual steps when resolving Jira ticket or even testing changes in PR. This type of routine should have automated check in place but will defer to Data Eng (cc @catalintomai ) if they have current process/documentation.
