### ISSUE TITLE
Request for Documentation: Plugin starter template readme

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#454]
Mattermost user `christopher.poile` from https://community-daily.mattermost.com has requested the following be documented:

```
The only correct way to use the starter template is to fork and install from source.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/3k4y3oni1tfidga7c6e6qfcnzo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cpoile** [comment]
Actually, not needed.
