### ISSUE TITLE
Request for Documentation: Typo in plugin webapp developer documentation

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#489]
Mattermost user `lev.brouk` from https://community.mattermost.com has requested the following be documented:

```
Not sure where to notify this, but...
I have found some "typos" in this site: https://developers.mattermost.com/extend/plugins/webapp/reference/
My main problem is the sample:
```
const React = window.react;
const PostUtils = window['post-utils']; // import the post utilities
import PropTypes from 'prop-types';
import {makeStyleFromTheme} from 'mattermost-redux/utils/theme_utils';
```
The fields of window are not `react` and `post-utils`. They are actually `React` and `PostUtils`, so this example would not work.
On top of that, if we make the previous change, the linter will probably complain and tell you to write `const PostUtils = window['PostUtils']; ` like `const PostUtils = window.PostUtils 
Finally, here we are using the module `prop-types` instead of taking it directly from the window object, so it is a bit against what is said in the rest of the site.

With all that being said, I am not sure whether it should be changed in other parts of the site.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/iy47fesyht8kbk7qwkt7br46xh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by RohitJain13** [comment]
See is pull request https://github.com/mattermost/mattermost-developer-documentation/pull/572 address this, or if there is more needed.
