### ISSUE TITLE
contribute/server/developer-setup not rendering properly

### ISSUE THREAD

**Issue by mroe** [mattermost/mattermost-developer-documentation#506]
It looks like `contribute/server/developer-setup.md` is rendering correctly in my local Hugo installation, but fails on https://developers.mattermost.com/contribute/server/developer-setup/.

**Comment by mitchellroe** [comment]
I've tested in Firefox 68.4.1esr and Google Chrome 79.0.3945.130 on Debian 10.

![image](https://user-images.githubusercontent.com/51406825/72670883-f30fad00-3a10-11ea-847a-100a15c34e44.png)

**Comment by mitchellroe** [comment]
Here it is on my local Hugo installation:

![image](https://user-images.githubusercontent.com/51406825/72670909-4f72cc80-3a11-11ea-8c7f-748833306a7f.png)

**Comment by mitchellroe** [comment]
I was running hugo v0.54.0/extended from the base Debian repositories, from which I made the above screenshot.  I upgraded my local hugo installation to v0.62.2-83E50184, and my experience is the same as on <https://developers.mattermost.com/contribute/server/developer-setup/>.

**Comment by mitchellroe** [comment]
Looks like it broke with Hugo v0.60.0; v0.59.1 works fine.  I'll look through the release notes to see if there's something they changed which would cause this behavior.
https://github.com/gohugoio/hugo/releases/tag/v0.60.0

**Comment by mitchellroe** [comment]
They switched from Blackfriday to Goldmark.
https://gohugo.io/news/0.60.0-relnotes/

Adding their recommended yaml block at the top of the file allows the HTML to be rendered.

```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```

**Comment by hanzei** [comment]
Fixed via https://github.com/mattermost/mattermost-developer-documentation/pull/509
