### ISSUE TITLE
Style Issues (General)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-developer-documentation#51]
1) Add "Beta" label to sidebar as well
![image](https://user-images.githubusercontent.com/13119842/33384447-0ea6ed78-d4f4-11e7-97a1-8b2878b2808e.png)

2) For the subsection headings, should the title be of the form `Web App Plugins: Reference`, or is that redundant?

Completely 0/5, just wondering if someone lands on the page, is it obvious what reference they're looking at (until they check the sidebar, which may be more crowded once we add the other sections to the site)

![image](https://user-images.githubusercontent.com/13119842/33384576-64d48f02-d4f4-11e7-88a1-b67f753e6eed.png)

**Comment by ccbrown** [comment]
2. I think the titles probably would be better off saying something like "Web App Plugins: Reference". At the very least, the tabs really need to say something more than "Reference":

<img width="1792" alt="screen shot 2017-11-29 at 10 06 00 pm" src="https://user-images.githubusercontent.com/1731074/33412567-b56d56ee-d551-11e7-84ac-cb383022d372.png">

**Comment by jwilander** [comment]
Working on this now
