### ISSUE TITLE
Request for Documentation: testing doc

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#557]
Mattermost user `erkage` from https://community.mattermost.com has requested the following be documented:

```
fasda

dasdasdas
```

See the original post [here](https://community.mattermost.com/_redirect/pl/dor5zq1697b3jkmxrt8kmetade).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by erkage** [comment]
sorry, just testing this feature! can be deleted!
