### ISSUE TITLE
Outdated Content of Quick Start > Server plugins

### ISSUE THREAD

**Issue by Nienzu** [mattermost/mattermost-developer-documentation#566]
As the sample code for plugin.go in Quick Start > Server plugins
![擷取](https://user-images.githubusercontent.com/11226260/76951078-07efba80-6946-11ea-9b29-e84e5b2d0848.PNG)

when execute `go build -o plugin.exe plugin.go`  would be error. And the message is below:

```
plugin.go:7:2: cannot find package "github.com/mattermost/mattermost-server/v5/plugin" in any of:
        /usr/local/go/src/github.com/mattermost/mattermost-server/v5/plugin (from $GOROOT)
        /home/tommy/go/src/github.com/mattermost/mattermost-server/v5/plugin (from $GOPATH)

```

So, I try to change the import line from 
```
import (
	"fmt"
	"net/http"

	"github.com/mattermost/mattermost-server/v5/plugin"
)
```
to 
```
import (
	"fmt"
	"net/http"

	"github.com/mattermost/mattermost-server/plugin"
)
```

Then it work fine.

**Comment by Nienzu** [comment]
I would like to help fix this issue, but I can not find the file location for the sample code for plugin.go.

**Comment by hanzei** [comment]
Hey @Nienzu,

Thanks for your report. Did you tried using Go Modules for dependency managment? If you run `go mod init` before running `go build` it works fine.

**Comment by Nienzu** [comment]
Hi @hanzei ,

It works! Thank you :>
