### ISSUE TITLE
Request for Documentation: Deprecate old guidance on how to add plugins to community

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#580]
Mattermost user `lev.brouk` from https://community-daily.mattermost.com has requested the following be documented:

```
Asking here (as per https://developers.mattermost.com/extend/plugins/community_process/ ) to begin the process to get a plugin added to community: https://github.com/mkraft/mattermost-plugin-whentochat
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/4hmqsf7g5brizgxp5hm5gf9uyc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by hanzei** [comment]
@levb What exactly needs up the updated in our docs?

**Comment by cwarnermm** [comment]
@levb - Can you provide some additional context for this documentation request, please?
