### ISSUE TITLE
Help Wanted: Allow showing of drafts using a query string in the URL

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-developer-documentation#59]
It would be nice to be able to see the draft pages using a special URL.

**Comment by hanzei** [comment]
I don't thing this is possible with hugo. If `draft` is set to `true`, hugo just ignores these pages.

**Comment by jwilander** [comment]
Sure but I bet we could write a bit of custom code or templating to do this

**Comment by cwarnermm** [comment]
Adding the **preview-environment** to a PR generates a preview of the site on each code commit. Closing.
