### ISSUE TITLE
Request for Documentation: make webapp-debug

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#597]
Mattermost user `christopher` from https://community-daily.mattermost.com has requested the following be documented:

```
Asked in a DM by @alber.john:
> Like in Vue JS/ React JS we have to serve mode in which we can see all the changes immediately, but in while matter most plugins development need to create a build then zip file and i load into the admin console and changes the changes. is there any quick way in which a can check my changes run time? 

Ya there is a way to see changes quicker. If you look at the jira plugin there is a make target called `webapp-debug` if you copy that (and related) into your Makefile and run that, you should be able to reload your webapp changes live: https://github.com/mattermost/mattermost-plugin-jira/blob/master/Makefile#L242

You will need to setup `MM_SERVICESETTINGS_SITEURL` `MM_ADMIN_USERNAME` and `MM_ADMIN_PASSWORD` in order for that to work. If you set those. `make deploy` will automatically install the plugin server side as well. 
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/1xg3dxw5kj8htjezht5zz5j94c).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by crspeller** [comment]
*@christopher attached a* [message](https://community-daily.mattermost.com/core/pl/b1szzfbhkb84tm6d5ykuqq1tfr) *from @maria.nunez*
We should include this into the [Quick Start](https://developers.mattermost.com/extend/plugins/webapp/hello-world/) webapp reference

**Comment by cwarnermm** [comment]
@crspeller - Would you be open to creating a PR with the requested documentation updates?

**Comment by crspeller** [comment]
Request is old and out of date. I guess the documentation team is not doing doc up requests anymore?
