### ISSUE TITLE
Request for Documentation: Add step to run webhook test server to e2e docs. 

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#613]
Mattermost user `christopher` from https://community-daily.mattermost.com has requested the following be documented:

```
`npm run start:webhook`
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/xgwsusoagbfztf7rbmgrgfrfgw).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@crspeller - Would you be open to creating a PR for this requested documentation update?

**Comment by crspeller** [comment]
Request is old and out of date.
