### ISSUE TITLE
Request for Documentation: Document Test Server labels

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#618]
Mattermost user `hanzei` from https://community.mattermost.com has requested the following be documented:

```
Did the Could Test Server always been an EE server without a license? I swear they used to also include a license. 
```

See the original post [here](https://community.mattermost.com/_redirect/pl/hjrneszpmjra5qgnj47w7q7kmh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@hanzei - This Help Wanted ticket has been idle for some time. Would you be interested in creating a PR with the requested documentation updates?

**Comment by hanzei** [comment]
I don't have enough context to do that. Maybe Cloud team would be right one to own this ticket as they also own the PR servers.

**Comment by Sonichigo** [comment]
@cwarnermm Can i take this issue?

**Comment by cwarnermm** [comment]
Hello @Sonichigo! We would welcome your help with this documentation issue! You'd be updating this [page](https://developers.mattermost.com/contribute/getting-started/labels/) on the developers.mattermost.com site, and you'd be updating the **Setup Cloud Test Server** description. I've assigned this ticket to you.

@jwilander - Can you confirm for us whether the **Setup Cloud Test Server** label triggers the creation of an Enterprise Edition test server, please? Would this server include an Enterprise license? Thanks for your help with this

**Comment by jwilander** [comment]
It does create an enterprise edition server.
