### ISSUE TITLE
Request for Documentation: Setup HA cluster

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#626]
Mattermost user `prapti.shrestha` from https://community-daily.mattermost.com has requested the following be documented:

```
##### Steps to setup HA cluster
Notes:
- See https://docs.mattermost.com/deployment/cluster.html for more info.
- Same steps can be ported to docker-compose to easily spin up the HA cluster.


1. Start database
```bash
docker run -d --name db -e POSTGRES_USER=mmuser -e POSTGRES_PASSWORD=mmuser_password -e POSTGRES_DB=mattermost mattermost/mattermost-prod-db
```

2. Start Minio as file storage
a. Start its docker image
```bash
docker run -d --name minio -p 9000:9000 -e MINIO_ACCESS_KEY=minioaccesskey -e MINIO_SECRET_KEY=miniosecretkey minio/minio server /data
```
b. Add `mattermost-test` as main folder
```bash
docker exec minio sh -c 'mkdir -p /data/mattermost-test'
```
c. Confirm that it's running by visiting ``localhost:9000`` and enter access/secret keys.

3. Start application servers
a. Save attached ``config.json`` to a folder
```bash
/tmp/mm/config/config.json
```
b. Grant permission to ``/tmp``.  Below is grant to all but correct approach is to grant specific user/group only.
```bash
sudo chmod -R a+rwx /tmp
```
c. Spin up the first application server and visit ``localhost:8065`` if working properly.
```bash
docker run -d --link db --link minio -p 8065:8065 -v /tmp/mm/config/config.json:/mattermost/config/config.json -v /tmp/mm/:/tmp/ --name app mattermost/mattermost-enterprise-edition:master
```
d. Then the other application server and visit ``localhost:8066`` if working properly.
```bash
docker run -d --link db --link minio --link app -p 8066:8065 -v /tmp/mm/config/config.json:/mattermost/config/config.json -v /tmp/mm/:/tmp/ --name app1 mattermost/mattermost-enterprise-edition:master
```

4. Expose the cluster with Nginx
a. Download and install Nginx
b. Save attached ``ha-mattermost`` nginx conf as ``/etc/nginx/sites-available/mattermost`` and link to enable.
```bash
sudo ln -s /etc/nginx/sites-available/ha-mattermost /etc/nginx/sites-enabled/ha-mattermost
```
c. Start Nginx
```
sudo systemctl start nginx
```
d. Should return without error and ``localhost`` or ``localhost:80`` should be accessible. ``localhost:8065`` and ``localhost:8066`` should still be accessible.

###### That's it! You've successfully setup an HA cluster.

5. Want to inspect the logs, especially of the server? Simply do ``docker logs -f [name]``, so for the first application server named as `app` 
```bash
docker logs -f app
```
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/9s8s1fctrbgutkre85uhnp9crc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by haardikdharma10** [comment]
Hey @DHaussermann, can you help me with the file, where I need to document this?

**Comment by cwarnermm** [comment]
@svelle - Can you please confirm whether the functionality above has been ported to docker-compose to support the creation of high availability clusters?

**Comment by svelle** [comment]
@cwarnermm the steps above are not related to the mattermost/docker repository. If I understand correctly this issue here is meant to spin up a local high availability setup which is not what the docker repository is meant to do.

**Comment by cwarnermm** [comment]
Thanks, @svelle! Do we officially support local HA environment setups?

**Comment by svelle** [comment]
@cwarnermm I don't see any reason why we should, it's nonsensical because it defeats the purpose of high availability. so no we don't.

If it's meant for development purposes yeah sure, but that's outside of our domain and also "unsupported" since it's meant for development/testing only.

hope that helps :)

**Comment by cwarnermm** [comment]
This helps a lot, @svelle. Based on your input, I'm closing this ticket.
