### ISSUE TITLE
Document theme CSS variables in plugin development guide

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-developer-documentation#630]
Sometimes plugins just have to rely on injecting CSS into the page for styling, for example, when a 3rd party React component doesn't accept custom styling. This creates a problem when trying to match Mattermost's dynamic theme with the component.

However, one can very easily use CSS variables which Mattermost already has over at https://github.com/mattermost/mattermost-webapp/blob/master/sass/base/_css_variables.scss

I just discovered it while debugging something and feel it would have made my life easier if I knew this existed all this time 😛 .

I'd like to suggest documenting this officially as a way of styling plugins dynamically based on the theme, in addition to [`theme` React prop](https://developers.mattermost.com/extend/plugins/webapp/reference/#theme)

**Comment by harshilsharma63** [comment]
I can work on this if this is accepted.

**Comment by hanzei** [comment]
That would be awesome, thanks @harshilsharma63 :+1:

**Comment by harshilsharma63** [comment]
@hanzei I've created the PR - https://github.com/mattermost/mattermost-developer-documentation/pull/632

**Comment by harshilsharma63** [comment]
This is how it looks <img width="665" alt="Screenshot 2020-05-31 at 4 51 33 PM" src="https://user-images.githubusercontent.com/8211068/83351134-fde33280-a35e-11ea-82e8-ac41ecea0769.png">

**Comment by hanzei** [comment]
Thanks @harshilsharma63 :+1: I've requested reviews for your PR

**Comment by harshilsharma63** [comment]
@hanzei thank you!
