### ISSUE TITLE
Closing notification takes me to the top of the page

### ISSUE THREAD

**Issue by vighnesh-r** [mattermost/mattermost-developer-documentation#673]
There is a notification that says **We are hiring**.

When I try to close that by clicking the **x** on the bar, it sets the URL fragment to **#** which just scrolls me to the top. 

Sometimes, I am at the mid-bottom of the documentation and just to get space, I close the notification bar, but it scrolls me to the top. It is annoying to scroll back to the bottom where I was reading.

File responsible for this:
`/site/layouts/partials/notification.html`

**Comment by justinegeffen** [comment]
I've tested this and it looks like it's been resolved. @vighnesh-r, please let us know if it happens again! Thank you. :)
