### ISSUE TITLE
Addition to Mobile E2E Testing documentation

### ISSUE THREAD

**Issue by avasconcelos114** [mattermost/mattermost-developer-documentation#693]
I just got around to setting up mobile E2E testing with detox and would like to add a note on the documentation recommending people to seed their local environment with the `make test-data` (or `mattermost sampledata`) command. 
Similar to how it's already been added to the [webapp's E2E documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/#quick-overview-on-how-to-run-e2e-testing)

Possibly also adding the fact that you can set the `SITE_URL`, `ADMIN_USERNAME`, and `ADMIN_PASSWORD` env vars would be beneficial to making testing more accessible to people

Would it make sense to add this as a new page called "Local Environment Setup" under "Mobile End-to-End Testing"?

**Comment by cwarnermm** [comment]
Thank you for this great documentation recommendation, @avasconcelos114. I apologize that you didn't receive a response sooner. Are you interested in creating a PR for this documentation update? It would make sense to add this new content as a new section on the [Mobile End-to-End Testing](https://developers.mattermost.com/contribute/mobile/e2e/) page.

**Comment by cwarnermm** [comment]
CC @simcard0000 for visibility

**Comment by simcard0000** [comment]
@cwarnermm Thanks for the ping! It totally can be worked on right now (and made into a PR), but I'll also make a note of this issue in the overall state of (e2e) testing documentation file I made and sent in the [Community Onboarding Refresh 2022 channel earlier](https://community.mattermost.com/core/pl/thnpsd3oaiyuxxeh91eszpmwsr).
