### ISSUE TITLE
[Help Wanted] Mobile Usability issues detected on https://developers.mattermost.com/

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-developer-documentation#722]
See below

![image](https://user-images.githubusercontent.com/13119842/97360450-992bf580-1874-11eb-867f-f3a25218b87b.png)

Unfortunately the report doesn't contain which pages are causing these issues, so this ticket will involve
1. investigating where the issues occur
2. resolving the issues

**Comment by JorgeMadson** [comment]
I will try it.

**Comment by JorgeMadson** [comment]
Sorry, have no ideia where this is happening.

**Comment by jasonblais** [comment]
@JorgeMadson thank you for helping investigate! 

@justinegeffen do you know if there's a way to find out where this mobility issue exists? I tried to investigate as well, but couldn't find where it's happening.

**Comment by justinegeffen** [comment]
That is very odd. It's not in our search console properties (as you probably saw). I've raised it with the Marketing team.

**Comment by lucievr** [comment]
I think I've found the issue, @jasonblais. It only happens on iPhone 5/SE and similar sized mobile phones.

Happy to submit a PR!

![mattermost-docs](https://user-images.githubusercontent.com/46979603/106809394-eb4a9700-666b-11eb-9383-6261828ba8b1.jpg)

**Comment by jasonblais** [comment]
Thank you @lucievr! Would love to see a PR if you're open to help resolve
