### ISSUE TITLE
The server contribution docs say to rebase off master, but we encourage merging instead

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#728]
Item 9 of the [Server Workflow](https://developers.mattermost.com/contribute/server/developer-workflow/#workflow) docs says:

> Respond to feedback on your pull request and make changes as necessary by committing to your branch and pushing it. You might need to rebase your changes if another pull request creates conflicts.

We can instead of have something such as:

> Once a PR is submitted it's a best practice to avoid rebasing on the base branch or force-pushing. Jesse, a developer at Mattermost, mentions this in his blog article [Submitting Great PRs](https://mattermost.com/blog/submitting-great-prs). When the PR is merged, all the PR's commits are automatically squashed into one commit, so you don't need to worry about having multiple commits on the PR.

**Comment by mickmister** [comment]
Maybe this should go in a different spot altogether, since it affects every repo, and not just the server repo. @justinegeffen Any thoughts?

**Comment by haardikdharma10** [comment]
Hi @mickmister, I think the [Code Review](https://developers.mattermost.com/contribute/getting-started/code-review/) docs will be a good place to have something which you mentioned. Let me know if that sounds good and I will help make the changes :)
cc @justinegeffen

**Comment by justinegeffen** [comment]
Yeah that's a good idea, @haardikdharma10. I'm happy with that. :)
