### ISSUE TITLE
Change npm -g install react-native-cli to sudo npm -g install react-native-cli

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/mattermost-developer-documentation#732]
When setting up the mobile development environment, the developer documentation [here](https://developers.mattermost.com/contribute/mobile/developer-setup/#install-react-native-cli-tools) mentions this:

<img width="805" alt="Screenshot 2020-11-14 at 1 18 32 AM" src="https://user-images.githubusercontent.com/53044263/99115012-c9ff7f00-2617-11eb-84fb-46f5610370f0.png">

The following command ran into a warning and several errors which can be seen in the screenshot below:

<img width="567" alt="Screenshot 2020-11-13 at 5 11 00 PM" src="https://user-images.githubusercontent.com/53044263/99115177-0206c200-2618-11eb-8cf3-a27a905c16dd.png">

This basically occurs because npm has no write access. Changing it to **sudo npm -g install react-native-cli** worked perfectly fine because we ran the command as root/Administrator. Maybe the documentation should reflect this change?

**Comment by TaylorWesker** [comment]
Can you assign this to me please ?
