### ISSUE TITLE
Hidden Environment Variables are Unavailable in Builds Triggered by PRs from Forks

### ISSUE THREAD

**Issue by MusikPolice** [mattermost/mattermost-developer-documentation#78]
Our build process utilizes hidden environment variables to protect private information like our AWS, GitHub, and YouTube API credentials. As a security precaution, these variables [are not available in builds that are triggered by a PR submitted from a fork of the repo](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions). We'll need to modify the build process to avoid executing the steps that require these variables in this case. See #77 for details.

**Comment by MariadeAnton** [comment]
Hey @MusikPolice  - I checking out open issues and noticed that this one can be closed since you're no longer using Travis CI: https://github.com/mattermost/mattermost-developer-documentation/commit/25f30e65d5087cfd1252bfabdb97fa447c20b2fc 💪

**Comment by hanzei** [comment]
Good catch @MariadeAnton. I think this can be closed
