### ISSUE TITLE
Documentation page styling

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-developer-documentation#8]
Need some better styling for the documentation pages.

Main needs:
- Better text size
- Mattermost colors
- Anything improving readability

**Comment by ccbrown** [comment]
Would we be able to steal someone's time to get a PM-approved mock up for the styling?

I'd like to add some images / visuals kinda like what you see throughout Apple's documentation, but I feel like I should wait until we have look and feel figured out.

**Comment by jwilander** [comment]
@jasonblais do you think we could appropriate some of your and @asaadmahmood's time to help us with the styling here?

**Comment by jwilander** [comment]
Chatted with JB, he's looking into getting some of AM's time for this

**Comment by jasonblais** [comment]
Have posted about getting Charles' or Asaad's help with a mock up + feedback on the general plan (as mentioned at https://github.com/mattermost/mattermost-developer-documentation/issues/10) in a Marketing channel.

Will post an update back here,

**Comment by jasonblais** [comment]
@ccbrown @jwilander Just an update that we should be able to get a sample mockup from Charles this week
