### ISSUE TITLE
Resolve soft 404 page crawl errors with 301 redirects

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/mattermost-developer-documentation#856]
The following two documentation pages on https://developers.mattermost.com currently include links to content that has been moved to the Mattermost Handbook:
- https://developers.mattermost.com/internal/rd-teams/
- https://developers.mattermost.com/internal/plugin-release-process/

These moved content links result in soft 404 errors when search engines crawl these pages of this site. To resolve these soft 404 errors, a 301 redirect must be added for each page that automatically takes page visitors to the new page URL.

- The first link above needs to auto-redirect to: https://handbook.mattermost.com/operations/research-and-development
- The second link above needs to auto-redirect to: https://handbook.mattermost.com/operations/research-and-development/engineering/plugin-release-process

**Comment by ewwollesen** [comment]
@cwarnermm I created a [PR](https://github.com/mattermost/mattermost-developer-documentation/issues/856) for this if you want to take a look.

I did check [Google developer docs for 301 redirects](https://developers.google.com/search/docs/advanced/crawling/301-redirects?hl=en&visit_id=637637194365272565-1217129624&rd=1#metarefresh) and it does appear that this is a valid method for a permanent redirect. I also found another redirect in the MM developer docs that was done similarly, so hopefully this is what you were wanting with this issue.

**Comment by cwarnermm** [comment]
Thanks so much @ewwollesen!
