### ISSUE TITLE
Help Wanted: Mattermost Apps documentation and examples

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/mattermost-developer-documentation#870]
We have a large amount of content that needs to be written for Apps. 

You can take a look at the Jira epic here: https://mattermost.atlassian.net/browse/MM-33921 (filter the issues by "Status" to see the open ones). The open issues are all up for grabs. 

The App's Documentation/content lives here (Production Site): https://developers.mattermost.com/integrate/apps/ 
and the [source content lives here](https://github.com/mattermost/mattermost-developer-documentation/tree/master/site/content/integrate/apps) (Feel free to start editing from here): 

Some things to keep in mind:
- This repo uses ['Hugo'](https://www.markdownguide.org/tools/hugo/) for the docs - some familiarity is helpful, but not required.
- You can submit code changes and samples, but please follow [this process](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/).
- You can write docs, but before you do so, take a look at our [Style Guide](https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide).
- Please submit each Jira issue as a separate PR.

Interested but have questions? Come on over to the [Docathon 2021 channel](https://community.mattermost.com/core/channels/docathon2021) and we'll be happy to help.

**Comment by aaronrothschild** [comment]
@justinegeffen I changed the description slightly...otherwise,LGTM

**Comment by mickmister** [comment]
@justinegeffen Do you have a particular issue in mind that would be a good first issue for a contributor? Looking at the open tickets in the Apps Documentation epic linked in the issue description, I don't think any of the issues would be applicable to anyone without extensive knowledge of the framework.

**Comment by neflyte** [comment]
A lot of this work has been done by a few recent PRs.
This issue should be re-visited for any specific information that needs to be documented above what now exists.

@justinegeffen Thoughts?

**Comment by cwarnermm** [comment]
Thanks, @neflyte. I agree that we can close this issue and open new issues if information gaps are discovered.
