### ISSUE TITLE
Plugin help wanted ticket links are broken

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#941]
The links pointing to plugin help wanted tickets on https://developers.mattermost.com/contribute/plugins and https://github.com/mattermost/mattermost-server/issues/12656 show a 404 on GitHub when the links are clicked. The link is supposed to go to an issue search query that filters on help wanted tickets in plugin projects.

Here's the [link](https://github.com/search?q=repo%3Amattermost%2Fmattermost-plugin-agenda+repo%3Amattermost%2Fmattermost-plugin-antivirus+repo%3Amattermost%2Fmattermost-plugin-autolink+repo%3Amattermost%2Fmattermost-plugin-aws-SNS+repo%3Amattermost%2Fmattermost-plugin-custom-attributes+repo%3Amattermost%2Fmattermost-oembed-plugin+repo%3Amattermost%2Fmattermost-plugin-giphy+repo%3Amattermost%2Fmattermost-plugin-github+repo%3Amattermost%2Fmattermost-plugin-gitlab+repo%3Amattermost%2Fmattermost-plugin-google-calendar+repo%3Amattermost%2Fmattermost-plugin-jenkins+repo%3Amattermost%2Fmattermost-plugin-jira+repo%3Amattermost%2Fmattermost-plugin-msoffice+repo%3Amattermost%2Fmattermost-plugin-solar-lottery+repo%3Amattermost%2Fmattermost-plugin-suggestions+repo%3Amattermost%2Fmattermost-plugin-todo+repo%3Amattermost%2Fmattermost-plugin-webex+repo%3Amattermost%2Fmattermost-plugin-welcomebot+repo%3Amattermost%2Fmattermost-plugin-zoom+repo%3Amattermost%2Fmattermost-plugin-msteams-meetings+is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22help+wanted%22+label%3A%22up+for+grabs%22+&amp;ref=simplesearch) for the "All Plugins Up for Grabs" query

**Comment by haardikdharma10** [comment]
The links seem to be working fine for me @mickmister. Am I missing something here?

**Comment by mickmister** [comment]
@haardikdharma10 Hmm I see. It's broken on my phone because it tries to open the search in the mobile app I use called FastHub, which doesn't handle the URL properly. I originally saw it on my friend's phone who does not use the same app so I figured the query was broken or something. I suppose there's nothing to do here. I'll look into it if I see it happen again (excluding the case of the FastHub app). Thanks @haardikdharma10!

**Comment by mickmister** [comment]
@haardikdharma10 Now that I think about it, there may have temporarily been an issue on GitHub's side when I saw the issue occur on my friend's device, as GitHub actually returned a 404 and he's not using the same FastHub app. Either way, still nothing for us to fix on our side.
