### ISSUE TITLE
Help Wanted: Broken Link on Contribution Checklist

### ISSUE THREAD

**Issue by bdoodo** [mattermost/mattermost-developer-documentation#986]
On the page https://developers.mattermost.com/contribute/getting-started/contribution-checklist/, the 'guides' link in 11) is broken. 

The link points to a missing page here: https://handbook.mattermost.com/operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/submitting-documentation-with-your-pr

**Comment by cwarnermm** [comment]
Thank you, @bdoodo! Would you be open to creating a PR that fixes this broken link?

**Comment by akshitarora921** [comment]
@cwarnermm I will take this. :)

**Comment by akshitarora921** [comment]
@cwarnermm Can you please confirm the correct like as https://developers.mattermost.com/blog/submitting-great-prs/?

**Comment by cwarnermm** [comment]
@akshitarora921 - Please use https://handbook.mattermost.com/operations/research-and-development/product/technical-writing-team-handbook#submit-documentation-with-your-pr-community for the link correction. Thank you!
