### ISSUE TITLE
The favicon is not visible in the dark-mode

### ISSUE THREAD

**Issue by akshitarora921** [mattermost/mattermost-developer-documentation#997]
The favicon of https://developers.mattermost.com/ does not have a white background but the favicon of https://mattermost.com/ has a white background due to which the favicon of the developer's website is not visible in dark mode.
Attaching the screenshot of tabs.
![image](https://user-images.githubusercontent.com/11087313/151503920-7bd9d8f4-3527-4937-8398-9cb127d17ea6.png)

**Comment by cwarnermm** [comment]
Thanks, @akshitarora921! I've alerted our Marketing team to this issue.

**Comment by akshitarora921** [comment]
@cwarnermm, I can work on this issue if you can provide me the correct favicon image.

**Comment by cwarnermm** [comment]
Very much appreciated, @akshitarora921! This issue is being reviewed by our Marketing team. I'll let you know if further action is required via a PR. Thank you!

**Comment by cwarnermm** [comment]
@akshitarora921 - Good news! The developers.mattermost.com site was updated recently with a new favicon that's easier to see in dark mode. When you visit the site, you should see this new favicon too. Please let me know if that's not the case. Closing this ticket.
